include(${CMAKE_CURRENT_SOURCE_DIR}/compiler_target.cmake)

compiler_target(${CMAKE_C_COMPILER} CMAKE_C_COMPILER_TARGET)
compiler_target(${CMAKE_CXX_COMPILER} CMAKE_CXX_COMPILER_TARGET)

message(STATUS "CMAKE_C_COMPILER_TARGET = " ${CMAKE_C_COMPILER_TARGET})
message(STATUS "CMAKE_CXX_COMPILER_TARGET = " ${CMAKE_CXX_COMPILER_TARGET})