include(${CMAKE_CURRENT_LIST_DIR}/compiler_target.cmake)

compiler_target(${CMAKE_C_COMPILER} CMAKE_C_COMPILER_TARGET)
compiler_target(${CMAKE_CXX_COMPILER} CMAKE_CXX_COMPILER_TARGET)

compiler_target(${CMAKE_C_COMPILER} AUTOTOOLS_HOST_TRIPLET)
compiler_target(gcc AUTOTOOLS_BUILD_TRIPLET)