find_program(COMPILER_CACHE_PROGRAM NAMES sccache ccache)

if(COMPILER_CACHE_PROGRAM)
    message(STATUS "Using compiler cache: ${COMPILER_CACHE_PROGRAM}")
    
    get_filename_component(CACHE_BINARY_NAME ${COMPILER_CACHE_PROGRAM} NAME)

    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ${COMPILER_CACHE_PROGRAM})
    
    if(CACHE_BINARY_NAME STREQUAL "ccache")
        set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ${COMPILER_CACHE_PROGRAM})
    endif()

    set(CCACHE_CC "${COMPILER_CACHE_PROGRAM} ${CMAKE_C_COMPILER}")
    set(CCACHE_CXX "${COMPILER_CACHE_PROGRAM} ${CMAKE_CXX_COMPILER}")
else()
    set(CCACHE_CC "${CMAKE_C_COMPILER}")
    set(CCACHE_CXX "${CMAKE_CXX_COMPILER}")
endif()
