find_program(CCACHE_PROGRAM ccache)

if(CCACHE_PROGRAM)
    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ${CCACHE_PROGRAM})
    set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ${CCACHE_PROGRAM})
endif(CCACHE_PROGRAM)

if(CCACHE_PROGRAM)
    set(CCACHE_CC "${CCACHE_PROGRAM} ${CMAKE_C_COMPILER}")
    set(CCACHE_CXX "${CCACHE_PROGRAM} ${CMAKE_CXX_COMPILER}")
else()
    set(CCACHE_CC "${CMAKE_C_COMPILER}")
    set(CCACHE_CXX "${CMAKE_CXX_COMPILER}")
endif()

macro(append_ccache_launcher_args CMAKE_ARGS_VAR)
    if(CCACHE_PROGRAM)
        list(APPEND ${CMAKE_ARGS_VAR}
            -DCMAKE_C_COMPILER_LAUNCHER=${CCACHE_PROGRAM}
            -DCMAKE_CXX_COMPILER_LAUNCHER=${CCACHE_PROGRAM})
    endif()
endmacro()